# Generated by Django 4.0.3 on 2022-04-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('location_image', models.ImageField(upload_to='')),
                ('location_price', models.SmallIntegerField()),
                ('location_text', models.TextField()),
                ('location_likes', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_orders', models.TextField()),
                ('user_likes', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
