# Generated by Django 4.0.3 on 2022-04-09 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.SmallIntegerField()),
                ('order_data', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='user_orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user_orders'),
        ),
    ]
